[package]
name = "mars"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = { workspace = true }

[dependencies]
lazy_static = { workspace = true }
regex = { workspace = true }
