[workspace]
members = [
    "mars",
    "mars_p3",
    "mars_py",
]

resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["Sean Ma"]
description = "My Rust/Python repo"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3
