[package]
name = "mars_p3"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
mars = { workspace = true }
pyo3 = { workspace = true }
